id: I7BD43D9D
ocr_import_info:
  timestamp: '2023-07-10T02:33:33.204915+00:00'
  batch_id: batch-21e2
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: PechaJobs
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-07-10 02:37:31.882126+00:00
last_modified: 2023-07-10 02:37:31.882133+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM3011
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM3011
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་ལ་འཇུག་པ་ཞེས་བྱ་བ་སོགས།
  languages:
  - bo
  author: ཟླ་བ་གྲགས་པ།
statistics:
  ocr_word_mean_confidence_index: 0.8875277783750052
  ocr_word_median_confidence_index: 0.949295
bases:
  I1NLM3011_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM3011_001
      total_pages: 208
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM3011_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.949295
      ocr_word_mean_confidence_index: 0.8875277783750052
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
